### ISSUE TITLE
Widget advisor feed

### ISSUE THREAD

**Issue by tmorrell** [caltechlibrary/cl-js#4]
The widget should list CaltechTHESIS: advisor when CaltechTHESIS_advisor is listed in people.json

This isn't critical because the javascript for embedding in web sites can be generated manually by taking a CaltechAUTHORS example and modifying the getPeopleJSON to use the "advisor" feed

**Comment by rsdoiel** [comment]
I'll do some testing if everything works my end I'll push this into the main branch of feeds for when we push out our next production verison.

**Comment by rsdoiel** [comment]
This looks good. I've added a test for this in the script folder (issue-4-test.md, issue-4-test.html).  I'm going to do a release v0.1.11 and then copy this into our main branch for feeds.
